// Code generated by protoc-gen-customized-protocols
// DO NOT EDIT!

export default class ProtoKey {
	public static KEY = {
		[11905] : actdice.G_INFO,
		[11778] : actdice.U_INIT_GRID_REWARD,
		[11779] : actdice.U_TURN,
		[11780] : actdice.U_BOSS_ATTACK,
		[11781] : actdice.U_SYNC_SCORE,
		[11782] : actdice.U_REFRESH_GRID_REWARD,
		[11783] : actdice.U_BUY_SHOP,
		[11784] : actdice.U_REWARD,
		[11785] : actdice.U_DICE_RECOVER,
		[11786] : actdice.U_SYNC_STAGE,
		[11787] : actdice.U_STAGE_REWARD,
		[1921] : activity.G_OPEN,
		[1794] : activity.U_JOIN,
		[1922] : activity.G_JOIN,
		[1795] : activity.U_END,
		[1796] : activity.U_CLOSE,
		[5505] : ad.G_INFO,
		[5378] : ad.U_USE_TICKET,
		[5379] : ad.U_FREE,
		[5380] : ad.U_SPEED,
		[5381] : ad.U_DOT,
		[5382] : ad.U_DISCOUNT_TIME,
		[257] : base.U_LOGIN,
		[385] : base.G_LOGIN,
		[258] : base.U_RELOGIN,
		[386] : base.G_RELOGIN,
		[259] : base.U_SYNC,
		[387] : base.G_SYNC,
		[375] : base.U_LANG,
		[376] : base.U_ZERO,
		[505] : base.G_FINISH,
		[378] : base.U_HEART,
		[506] : base.G_HEART,
		[507] : base.G_GMLEVEL,
		[380] : base.U_GM,
		[510] : base.G_ERROR,
		[511] : base.G_TIP,
		[7041] : buffcard.G_INFO,
		[10881] : card.G_INFO,
		[10754] : card.U_UP_LEVEL,
		[10755] : card.U_UP_STAR,
		[10756] : card.U_COMBINE,
		[10757] : card.U_EXCHANGE,
		[6273] : chapter.G_INFO,
		[6146] : chapter.U_UP_DEPARTMENT,
		[6147] : chapter.U_UP_ENTRY,
		[6148] : chapter.U_LAY_CARD,
		[6149] : chapter.U_UP_CHAPTER,
		[897] : currency.G_INFO,
		[770] : currency.U_UP_BIG,
		[895] : currency.U_CHECK_DIAMOND,
		[8065] : dailyad.G_INFO,
		[7938] : dailyad.U_ADD,
		[7939] : dailyad.U_REWARD,
		[6785] : dailydiscount.G_INFO,
		[6658] : dailydiscount.U_FLUSH,
		[6659] : dailydiscount.U_BUY,
		[11137] : dice.G_INFO,
		[11010] : dice.U_INJECT,
		[11011] : dice.U_REWARD,
		[11012] : dice.U_GATHER,
		[11013] : dice.U_REVIVAL,
		[11014] : dice.U_DOT,
		[7682] : event.U_DOT,
		[6017] : gift.G_INFO,
		[5890] : gift.U_ETIME,
		[1665] : guide.G_INFO,
		[1538] : guide.U_UPDATE,
		[1539] : guide.U_WEAK_DOT,
		[641] : item.G_INFO,
		[514] : item.U_OPEN,
		[10625] : level.G_INFO,
		[7170] : offline.U_REWARD,
		[2177] : other.G_INFO,
		[2050] : other.U_BACKSTAGE,
		[1409] : recharge.G_INFO,
		[1282] : recharge.U_ORDER,
		[1410] : recharge.G_ORDER,
		[1283] : recharge.U_CALLBACK,
		[1411] : recharge.G_CALLBACK,
		[1284] : recharge.U_REWARD,
		[11649] : savingpot.G_INFO,
		[11522] : savingpot.U_FULL,
		[5761] : shop.G_INFO,
		[5634] : shop.U_BUY,
		[11393] : shopcard.G_INFO,
		[11266] : shopcard.U_EXCHANGE,
		[11267] : shopcard.U_REFRESH,
		[6529] : task.G_INFO,
		[6402] : task.U_SYNC_BIG,
		[6403] : task.U_RECEIVE,
		[6404] : task.U_RECEIVE_STAGE,
		[7553] : urgenttask.G_INFO,
		[7426] : urgenttask.U_DEL_CD,
		[7427] : urgenttask.U_REWARD,

		"actdice.G_INFO" : 11905,
		"actdice.U_INIT_GRID_REWARD" : 11778,
		"actdice.U_TURN" : 11779,
		"actdice.U_BOSS_ATTACK" : 11780,
		"actdice.U_SYNC_SCORE" : 11781,
		"actdice.U_REFRESH_GRID_REWARD" : 11782,
		"actdice.U_BUY_SHOP" : 11783,
		"actdice.U_REWARD" : 11784,
		"actdice.U_DICE_RECOVER" : 11785,
		"actdice.U_SYNC_STAGE" : 11786,
		"actdice.U_STAGE_REWARD" : 11787,
		"activity.G_OPEN" : 1921,
		"activity.U_JOIN" : 1794,
		"activity.G_JOIN" : 1922,
		"activity.U_END" : 1795,
		"activity.U_CLOSE" : 1796,
		"ad.G_INFO" : 5505,
		"ad.U_USE_TICKET" : 5378,
		"ad.U_FREE" : 5379,
		"ad.U_SPEED" : 5380,
		"ad.U_DOT" : 5381,
		"ad.U_DISCOUNT_TIME" : 5382,
		"base.U_LOGIN" : 257,
		"base.G_LOGIN" : 385,
		"base.U_RELOGIN" : 258,
		"base.G_RELOGIN" : 386,
		"base.U_SYNC" : 259,
		"base.G_SYNC" : 387,
		"base.U_LANG" : 375,
		"base.U_ZERO" : 376,
		"base.G_FINISH" : 505,
		"base.U_HEART" : 378,
		"base.G_HEART" : 506,
		"base.G_GMLEVEL" : 507,
		"base.U_GM" : 380,
		"base.G_ERROR" : 510,
		"base.G_TIP" : 511,
		"buffcard.G_INFO" : 7041,
		"card.G_INFO" : 10881,
		"card.U_UP_LEVEL" : 10754,
		"card.U_UP_STAR" : 10755,
		"card.U_COMBINE" : 10756,
		"card.U_EXCHANGE" : 10757,
		"chapter.G_INFO" : 6273,
		"chapter.U_UP_DEPARTMENT" : 6146,
		"chapter.U_UP_ENTRY" : 6147,
		"chapter.U_LAY_CARD" : 6148,
		"chapter.U_UP_CHAPTER" : 6149,
		"currency.G_INFO" : 897,
		"currency.U_UP_BIG" : 770,
		"currency.U_CHECK_DIAMOND" : 895,
		"dailyad.G_INFO" : 8065,
		"dailyad.U_ADD" : 7938,
		"dailyad.U_REWARD" : 7939,
		"dailydiscount.G_INFO" : 6785,
		"dailydiscount.U_FLUSH" : 6658,
		"dailydiscount.U_BUY" : 6659,
		"dice.G_INFO" : 11137,
		"dice.U_INJECT" : 11010,
		"dice.U_REWARD" : 11011,
		"dice.U_GATHER" : 11012,
		"dice.U_REVIVAL" : 11013,
		"dice.U_DOT" : 11014,
		"event.U_DOT" : 7682,
		"gift.G_INFO" : 6017,
		"gift.U_ETIME" : 5890,
		"guide.G_INFO" : 1665,
		"guide.U_UPDATE" : 1538,
		"guide.U_WEAK_DOT" : 1539,
		"item.G_INFO" : 641,
		"item.U_OPEN" : 514,
		"level.G_INFO" : 10625,
		"offline.U_REWARD" : 7170,
		"other.G_INFO" : 2177,
		"other.U_BACKSTAGE" : 2050,
		"recharge.G_INFO" : 1409,
		"recharge.U_ORDER" : 1282,
		"recharge.G_ORDER" : 1410,
		"recharge.U_CALLBACK" : 1283,
		"recharge.G_CALLBACK" : 1411,
		"recharge.U_REWARD" : 1284,
		"savingpot.G_INFO" : 11649,
		"savingpot.U_FULL" : 11522,
		"shop.G_INFO" : 5761,
		"shop.U_BUY" : 5634,
		"shopcard.G_INFO" : 11393,
		"shopcard.U_EXCHANGE" : 11266,
		"shopcard.U_REFRESH" : 11267,
		"task.G_INFO" : 6529,
		"task.U_SYNC_BIG" : 6402,
		"task.U_RECEIVE" : 6403,
		"task.U_RECEIVE_STAGE" : 6404,
		"urgenttask.G_INFO" : 7553,
		"urgenttask.U_DEL_CD" : 7426,
		"urgenttask.U_REWARD" : 7427,
	};

	public static actdice = {
		G_INFO : "actdice.G_INFO",
		U_INIT_GRID_REWARD : "actdice.U_INIT_GRID_REWARD",
		U_TURN : "actdice.U_TURN",
		U_BOSS_ATTACK : "actdice.U_BOSS_ATTACK",
		U_SYNC_SCORE : "actdice.U_SYNC_SCORE",
		U_REFRESH_GRID_REWARD : "actdice.U_REFRESH_GRID_REWARD",
		U_BUY_SHOP : "actdice.U_BUY_SHOP",
		U_REWARD : "actdice.U_REWARD",
		U_DICE_RECOVER : "actdice.U_DICE_RECOVER",
		U_SYNC_STAGE : "actdice.U_SYNC_STAGE",
		U_STAGE_REWARD : "actdice.U_STAGE_REWARD",
	};

	public static activity = {
		G_OPEN : "activity.G_OPEN",
		U_JOIN : "activity.U_JOIN",
		G_JOIN : "activity.G_JOIN",
		U_END : "activity.U_END",
		U_CLOSE : "activity.U_CLOSE",
	};

	public static ad = {
		G_INFO : "ad.G_INFO",
		U_USE_TICKET : "ad.U_USE_TICKET",
		U_FREE : "ad.U_FREE",
		U_SPEED : "ad.U_SPEED",
		U_DOT : "ad.U_DOT",
		U_DISCOUNT_TIME : "ad.U_DISCOUNT_TIME",
	};

	public static base = {
		U_LOGIN : "base.U_LOGIN",
		G_LOGIN : "base.G_LOGIN",
		U_RELOGIN : "base.U_RELOGIN",
		G_RELOGIN : "base.G_RELOGIN",
		U_SYNC : "base.U_SYNC",
		G_SYNC : "base.G_SYNC",
		U_LANG : "base.U_LANG",
		U_ZERO : "base.U_ZERO",
		G_FINISH : "base.G_FINISH",
		U_HEART : "base.U_HEART",
		G_HEART : "base.G_HEART",
		G_GMLEVEL : "base.G_GMLEVEL",
		U_GM : "base.U_GM",
		G_ERROR : "base.G_ERROR",
		G_TIP : "base.G_TIP",
	};

	public static buffcard = {
		G_INFO : "buffcard.G_INFO",
	};

	public static card = {
		G_INFO : "card.G_INFO",
		U_UP_LEVEL : "card.U_UP_LEVEL",
		U_UP_STAR : "card.U_UP_STAR",
		U_COMBINE : "card.U_COMBINE",
		U_EXCHANGE : "card.U_EXCHANGE",
	};

	public static chapter = {
		G_INFO : "chapter.G_INFO",
		U_UP_DEPARTMENT : "chapter.U_UP_DEPARTMENT",
		U_UP_ENTRY : "chapter.U_UP_ENTRY",
		U_LAY_CARD : "chapter.U_LAY_CARD",
		U_UP_CHAPTER : "chapter.U_UP_CHAPTER",
	};

	public static common = {
	};

	public static currency = {
		G_INFO : "currency.G_INFO",
		U_UP_BIG : "currency.U_UP_BIG",
		U_CHECK_DIAMOND : "currency.U_CHECK_DIAMOND",
	};

	public static dailyad = {
		G_INFO : "dailyad.G_INFO",
		U_ADD : "dailyad.U_ADD",
		U_REWARD : "dailyad.U_REWARD",
	};

	public static dailydiscount = {
		G_INFO : "dailydiscount.G_INFO",
		U_FLUSH : "dailydiscount.U_FLUSH",
		U_BUY : "dailydiscount.U_BUY",
	};

	public static dice = {
		G_INFO : "dice.G_INFO",
		U_INJECT : "dice.U_INJECT",
		U_REWARD : "dice.U_REWARD",
		U_GATHER : "dice.U_GATHER",
		U_REVIVAL : "dice.U_REVIVAL",
		U_DOT : "dice.U_DOT",
	};

	public static event = {
		U_DOT : "event.U_DOT",
	};

	public static gift = {
		G_INFO : "gift.G_INFO",
		U_ETIME : "gift.U_ETIME",
	};

	public static guide = {
		G_INFO : "guide.G_INFO",
		U_UPDATE : "guide.U_UPDATE",
		U_WEAK_DOT : "guide.U_WEAK_DOT",
	};

	public static item = {
		G_INFO : "item.G_INFO",
		U_OPEN : "item.U_OPEN",
	};

	public static level = {
		G_INFO : "level.G_INFO",
	};

	public static offline = {
		U_REWARD : "offline.U_REWARD",
	};

	public static other = {
		G_INFO : "other.G_INFO",
		U_BACKSTAGE : "other.U_BACKSTAGE",
	};

	public static recharge = {
		G_INFO : "recharge.G_INFO",
		U_ORDER : "recharge.U_ORDER",
		G_ORDER : "recharge.G_ORDER",
		U_CALLBACK : "recharge.U_CALLBACK",
		G_CALLBACK : "recharge.G_CALLBACK",
		U_REWARD : "recharge.U_REWARD",
	};

	public static savingpot = {
		G_INFO : "savingpot.G_INFO",
		U_FULL : "savingpot.U_FULL",
	};

	public static shop = {
		G_INFO : "shop.G_INFO",
		U_BUY : "shop.U_BUY",
	};

	public static shopcard = {
		G_INFO : "shopcard.G_INFO",
		U_EXCHANGE : "shopcard.U_EXCHANGE",
		U_REFRESH : "shopcard.U_REFRESH",
	};

	public static task = {
		G_INFO : "task.G_INFO",
		U_SYNC_BIG : "task.U_SYNC_BIG",
		U_RECEIVE : "task.U_RECEIVE",
		U_RECEIVE_STAGE : "task.U_RECEIVE_STAGE",
	};

	public static urgenttask = {
		G_INFO : "urgenttask.G_INFO",
		U_DEL_CD : "urgenttask.U_DEL_CD",
		U_REWARD : "urgenttask.U_REWARD",
	};
}